version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    command: dumb-init bin/bundle exec puma
    volumes:
      - /home/deploy/apps/threeComponentApp/shared/public/assets:/app/log:/app/public/assets
      - /home/deploy/apps/threeComponentApp/shared/log:/app/log
    hostname: "netguru.application.production.web"
    labels:
      - "netguru.appname=threeComponentApp"
      - "netguru.stage=production"
    expose:
      - "3000"
  crono:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    volumes:
      - /home/deploy/apps/threeComponentApp/shared/log:/app/log
    hostname: "netguru.application.production.crono"
    command: dumb-init bin/bundle exec crono
    labels:
      - "netguru.appname=threeComponentApp"
      - "netguru.stage=production"
  sidekiq:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    volumes:
      - /home/deploy/apps/threeComponentApp/shared/log:/app/log
    hostname: "netguru.application.production.sidekiq"
    command: dumb-init bin/bundle exec sidekiq
    labels:
      - "netguru.appname=threeComponentApp"
      - "netguru.stage=production"