version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    command: dumb-init bundle exec puma -C config/puma.rb
    volumes:
      - /Users/piotr/Documents/projects/RoR_App/blog/app/assets:/app/public/assets
      - /Users/piotr/Documents/projects/RoR_App/blog/log:/app/log
    hostname: "netguru.application.production.web"
    labels:
      - "netguru.appname=threecomponentapp"
      - "netguru.stage=production"
    expose:
      - "3000"
  crono:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    volumes:
      - /Users/piotr/Documents/projects/RoR_App/blog/log:/app/log
    hostname: "netguru.application.production.crono"
    command: dumb-init bundle exec crono
    labels:
      - "netguru.appname=threecomponentapp"
      - "netguru.stage=production"
  sidekiq:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    volumes:
      - /Users/piotr/Documents/projects/RoR_App/blog/log:/app/log
    hostname: "netguru.application.production.sidekiq"
    command: dumb-init bash -c "bundle exec sidekiq"
    labels:
      - "netguru.appname=threecomponentapp"
      - "netguru.stage=production"